image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint  # скрипт тестирования

artifacts:
- path: artifacts\ * .nupkg

after_build:
  - git config --global user.email "ov.nattie@gmail.com"
  - git config --global user.name "tashakibanova"
  - npm run build
  - git add -A
  - git commit -m "Deploy to GitHub Pages"
  - git push origin gh-pages
