image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint  # скрипт тестирования

deploy:
  provider: Pages
  repo: tashakibanova/DnD # Замените на ваш GitHub username и имя репозитория
  branch: gh-pages # Публикуем в ветку gh-pages
  folder: dist # Указываем папку, которую нужно опубликовать
  auth_token:
    secure: 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 # Добавьте защищенный токен доступа к GitHub (см. ниже)
    draft: false
    prerelease: false
  on:
    branch: main # Публикуем только при успешной сборке ветки master
