image: Ubuntu2204  # образ для сборки

stack: node 20  # окружение

branches:
  only:
    - master  # ветка git

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint  # скрипт тестирования

artifacts:
- path: artifacts\ * .nupkg

deploy:
  provider: GitHub
  repo: "https://github.com/tashakibanova/DnD.git" # Замените на ваш GitHub username и имя репозитория
  branch: gh-pages # Публикуем в ветку gh-pages
  folder: dist # Указываем папку, которую нужно опубликовать
  auth_token:
    secure: UofPzrpOvB0/sk+/X1jalnFboit3ApgibpefBa8DKLk9I+CdbHc1Ec/L/h6G3cZb # Добавьте защищенный токен доступа к GitHub (см. ниже)
  on:
    branch: main # Публикуем только при успешной сборке ветки master
